name: scratch_clone
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  lottie: ^3.1.0
  flutter_bloc: ^9.1.1
  supabase_flutter: ^2.9.1
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_colorpicker: ^1.1.0
  image: ^4.5.3
  flutter_joystick: ^0.2.2
  json_annotation: ^4.8.0
  audioplayers: ^6.5.0
  collection: ^1.19.1
  file_picker: ^10.2.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  tflite_flutter: ^0.11.0
  camera: ^0.11.2
dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P.ttf

  assets:
    - assets/goku/walk/
    - assets/goku/idle/
    - assets/vegeta/idle/
    - assets/vegeta/walk/
    - assets/grid_image.jpg
    - assets/icons/
    - assets/sounds/
    - assets/lottie/joy_stick.json
    - assets/lottie/coin.json
